# Generated by Django 3.0.5 on 2022-02-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20220201_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('-date',), 'verbose_name': 'ticket', 'verbose_name_plural': 'tickets'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OP', 'open'), ('closed', 'Closed'), ('frozen', 'Frozen')], default='OP', max_length=30),
        ),
    ]
